# same per-process env as ~/.local/bin/claude-qwen, base URL overridable
KEY=$(<"$HOME/.config/claude-qwen/api_key")
MODEL="Qwen3.8-27B-Uncensored"
export ANTHROPIC_BASE_URL="${BASE:-http://127.0.0.1:8421}"
export ANTHROPIC_AUTH_TOKEN="$KEY"
unset ANTHROPIC_API_KEY CLAUDE_CODE_OAUTH_TOKEN CLAUDE_CODE_USE_BEDROCK CLAUDE_CODE_USE_VERTEX
export ANTHROPIC_MODEL="$MODEL" ANTHROPIC_DEFAULT_OPUS_MODEL="$MODEL" ANTHROPIC_DEFAULT_SONNET_MODEL="$MODEL" ANTHROPIC_DEFAULT_HAIKU_MODEL="$MODEL" CLAUDE_CODE_SUBAGENT_MODEL="$MODEL"
export ANTHROPIC_CUSTOM_MODEL_OPTION="$MODEL"
export CLAUDE_CODE_MAX_CONTEXT_TOKENS=131072 CLAUDE_CODE_DISABLE_1M_CONTEXT=1 CLAUDE_CODE_AUTO_COMPACT_WINDOW=131072 CLAUDE_AUTOCOMPACT_PCT_OVERRIDE=75
export CLAUDE_CODE_ATTRIBUTION_HEADER=0 CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC=1 API_TIMEOUT_MS=1800000 CLAUDE_CODE_SUBPROCESS_ENV_SCRUB=0
